### PR TITLE
User signin/signup changes, navbar upgrades, fix oauth, transactions migrated to admin dashboard, help page

### PR DESCRIPTION
**Pull request by nathanhtkd**
User Sign-in/Sign-up Workflow: Revamped the sign-in and sign-up processes for a smoother user experience, including streamlined forms and clearer navigation, also added callsigns .
Navbar Enhancements: Upgraded the navigation bar for enhanced usability and better visual integration 
OAuth Fix: Addressed issues with the OAuth authentication mechanism
Admin Dashboard Transactions: Migrated transaction management functionality into the admin dashboard

### CODE REVIEW

**Review by ekennedy1 — APPROVED** [review]
As a user, I want to be able to quickly search and filter the inventory checklist, so I can easily locate items that I want to checkout.

---Search bar was implemented as part of this pull request and all coding conventions that were agreed to were followed .

AC1: On the Member - Inventory page, there should be a search bar at the top of the list.

---The search bar exists for the inventory page and is correctly positioned on the page.

AC2: I should be able to enter a keyword or item name into the search bar.

---Keyword searching works to find the item that the user needs to be able to checkout.

DoD: 

Code Review Performed (Check coding standards, well formatted and documented)

Product Owner approved

Acceptance Criteria Met

---Definition of done is met through the acceptance criteria and product owner approval.

**Comment by nathanhtkd** [comment]
User Story: Support Plan

As a user, I want access to comprehensive help pages and a support plan, so that I can easily navigate the website, troubleshoot any issues I encounter, and feel confident in using the platform's features.

AC1: The website should include a visible "Help" or "Support" link/button on every page, ensuring users can easily access assistance no matter where they are. (located in the navbar, nice!)

AC2: For users seeking assistance, a "Contact Support" link should be present, giving them a quick route to reach out to a support representative.
_**This AC has not been met :( Please put a link for contact support **_

DoD: 
Code Review Performed (Check coding standards, well formatted and documented)
Product Owner approved (Tyler has approved in zoom code review)
Acceptance Criteria Met (checked)

**Comment by nathanhtkd** [comment]
Nice, I see the link to all the contacts!

**Comment by nathanhtkd** [comment]
User Story: Inventory Search
As a user, I want to be able to quickly search and filter the inventory checklist, so I can easily locate items that I want to checkout.

AC1: On the Member - Inventory page, there should be a search bar at the top of the list.
------ Nice, this is implemented in the top of the member inventory and works with my new card design
AC2: I should be able to enter a keyword or item name into the search bar.
------ This is implemented into the search bar

DoD: 
Code Review Performed (Check coding standards, well formatted and documented)
Product Owner approved (Tyler has approved in Code review call)
Acceptance Criteria Met (All are met)

**Comment by nathanhtkd** [comment]
User Story: Transaction Time Keeping
As an admin, I want to be able to approve transactions manually and see the time a transaction was made and approved, so that I can ensure that each transaction undergoes a thorough review, helping to identify and prevent fraudulent or unauthorized activities

AC1: On the Admin Dashboard - Transactions have time information
---- Nice, I see this implementation inside of our admin dashboard and the times are working
AC2: Admins should be able to manually approve any transaction
---- After some manual testing,  this functionality works and displays correctly onto our admin dashboard

Great work!

DoD: 
Code Review Performed (Check coding standards, well formatted and documented)
Product Owner approved
Acceptance Criteria Met

**Pull request merged**
